import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { cpSync, existsSync, mkdirSync, readdirSync } from 'fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/**
 * Sucht rekursiv unter `dir` nach Dateien, deren Name auf eines der
 * `patterns`-RegExps passt. Bewusst musterbasiert statt fester Dateinamen,
 * da sich Dateinamen zwischen Paketversionen ändern können (z. B.
 * "tf.min.js" vs. "tf.es2017.min.js") – lieber explizit warnen, wenn nichts
 * gefunden wird, als stillschweigend eine falsche Annahme zu treffen.
 */
function findFiles(dir, patterns) {
	const results = [];
	function walk(current) {
		let entries;
		try {
			entries = readdirSync(current, { withFileTypes: true });
		} catch {
			return;
		}
		for (const entry of entries) {
			const full = path.join(current, entry.name);
			if (entry.isDirectory()) {
				walk(full);
			} else if (patterns.some((p) => p.test(entry.name))) {
				results.push(full);
			}
		}
	}
	walk(dir);
	return results;
}

/**
 * Kopiert die fertigen UMD-Browser-Bundles von @tensorflow/tfjs und
 * @tensorflow/tfjs-tflite (z. B. tf.min.js, tf-tflite.min.js) sowie die
 * tfjs-tflite-WASM-Binärdateien unverändert in den Plugin-Ordner ("wasm/").
 *
 * WICHTIG: Diese Pakete werden NICHT mehr über esbuild gebündelt (siehe
 * OcrModelRunner.ts für die Begründung: führte zu "Failed to resolve module
 * specifier" bzw. "Cannot use import statement outside a module"). Sie
 * werden zur Laufzeit stattdessen per <script>-Tag nachgeladen – exakt wie
 * in Googles eigener tfjs-tflite-Dokumentation empfohlen. esbuild fasst den
 * Inhalt dieser Dateien nie an, sie werden 1:1 kopiert.
 *
 * Muss vor jedem Build/Watch laufen (nicht danach), sonst passiert nichts.
 */
function copyTfliteRuntimeAssets() {
    const dest = 'wasm';
    const tfDist = 'node_modules/@tensorflow/tfjs/dist';
    const tfliteDist = 'node_modules/@tensorflow/tfjs-tflite/dist';
    const tfliteWasmDir = path.join(tfliteDist, '..', 'wasm'); // Korrektur!

    if (!existsSync(tfDist) || !existsSync(tfliteDist)) {
        console.error(
            `[esbuild] WARNUNG: "${tfDist}" oder "${tfliteDist}" nicht gefunden. ` +
            `Sind @tensorflow/tfjs und @tensorflow/tfjs-tflite installiert?`
        );
        return;
    }

    mkdirSync(dest, { recursive: true });

    // 1. tf.min.js / tf.js (aus tfjs/dist)
    const tfJsFiles = findFiles(tfDist, [/^tf\.min\.js$/i, /^tf\.js$/i]);
    for (const file of tfJsFiles) {
        cpSync(file, path.join(dest, path.basename(file)));
    }

    // 2. tf-tflite.min.js / tf-tflite.js (aus tfjs-tflite/dist)
    const tfliteJsFiles = findFiles(tfliteDist, [/^tf-tflite\.min\.js$/i, /^tf-tflite\.js$/i]);
    for (const file of tfliteJsFiles) {
        cpSync(file, path.join(dest, path.basename(file)));
    }

    // 3. ALLE Dateien aus dem wasm-Ordner (neben dist)
    if (existsSync(tfliteWasmDir)) {
        let wasmFiles = findFiles(tfliteWasmDir, [/.*/]); // rekursiv alle Dateien
		wasmFiles = wasmFiles.filter(file => !path.basename(file).includes('_threaded'));
        for (const file of wasmFiles) {
            cpSync(file, path.join(dest, path.basename(file)));
        }
        console.log(`[esbuild] ${wasmFiles.length} Datei(en) aus wasm-Ordner kopiert.`);
    } else {
        console.error(`[esbuild] FEHLER: "${tfliteWasmDir}" nicht gefunden.`);
    }

    console.log(`[esbuild] Laufzeitdateien nach "${dest}/" kopiert.`);
}

copyTfliteRuntimeAssets();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
